### ISSUE TITLE
VP9 codec

### ISSUE THREAD

**Issue by ashar02** [lynckia/licode#1356]
After installation from source code on ubuntu 14.04. I disabled vp8 codec and made vp9 as default video codec in rtp_media_config.js. But when I joined the room video got stuck after few seconds. Am I doing any thing wrong?? Anyone can help?

**Comment by ashar02** [comment]
I verified using webrtc-internals that vp9 is selected as video codec.

**Comment by ashar02** [comment]
@jcague please comment?

**Comment by ashar02** [comment]
@jcague to run it correctly do I have to enable simulcast in my environment?

**Comment by jcague** [comment]
no you don't need to enable simulcast, I'll try to reproduce your issue shortly

**Comment by ashar02** [comment]
@jcague every solution in market is using vp9 to save bandwidth having same quality. In licode it starts properly but then it stops after few seconds. Are you able to produce it? Can you give me hint where to see in code to run it properly?

**Comment by jcague** [comment]
This issue could be related with the things @lodoyun solved in #1413 , have you tested with the last version in the master branch?

**Comment by ashar02** [comment]
Let me check and let you know today!!

**Comment by ashar02** [comment]
I checkout the code from master head. Use ubuntu 16.04. I changed the default: { rtpMappings: { vp8, opus }, extMappings } to default: { rtpMappings: { vp9, opus }, extMappings }, in file rtp_media_config.js

And ran the server and I noticed the problem persist. After few seconds remote video freezes.
<img width="1680" alt="Screen Shot 2019-06-05 at 6 23 21 PM" src="https://user-images.githubusercontent.com/1763187/58960159-ffb3fd80-87bf-11e9-8cb7-5ef99258e50a.png">
<img width="1680" alt="Screen Shot 2019-06-05 at 6 24 55 PM" src="https://user-images.githubusercontent.com/1763187/58960173-0b072900-87c0-11e9-9f11-a949efd3d7a4.png">
<img width="1680" alt="Screen Shot 2019-06-05 at 6 32 08 PM" src="https://user-images.githubusercontent.com/1763187/58960271-4ace1080-87c0-11e9-8c29-714b2dffa6a8.png">

So it seems that publisher is sending the stream correctly but at subscription end after few seconds it stops receiving the video stream in case of vp9.

**Comment by ashar02** [comment]
So how to narrow this issue?

**Comment by ashar02** [comment]
@jcague is there any impact of #1419 on vp9?

**Comment by jcague** [comment]
I don't think so, I'll try to reproduce this issue today though

**Comment by jcague** [comment]
@ashar02 can you check if it is fixed in #1420 please?

**Comment by ashar02** [comment]
@jcague sure!!

**Comment by ashar02** [comment]
@jcague great work!! Now it is working correctly :) with 1420

**Comment by ashar02** [comment]
One more question: will recording work with vp9 codec?
